### ISSUE TITLE
URW Nimbus font issue: Cyrillic small letter `te` (afii10084) has wrong glyph in italic and bold Italic style

### ISSUE THREAD

**Issue by tillkamppeter** [ArtifexSoftware/urw-base35-fonts#28]
[Bug 1871377](https://bugs.launchpad.net/ubuntu/+source/fonts-urw-base35/+bug/1871377) reported to Ubuntu:
```
It seems that cyrillic small letter `te` (afii10084) has wrong glyph in italic and bold Italic style: width is too big.
This issue presented in OpenType and Type1 URW Nimbus Sans fonts distribution.

I suggest to replace with the glyph of greek small `tau` letter.

Attaching here the screenshots of some example words contain small letter `te` with original (wide) and replaced glyph.
```
See screen shots and more info in the files and comments on the Ubuntu bug report.

**Comment by deekej** [comment]
Please, report this issue directly to (URW++) company. IIRC, Artifex only repackages the fonts & releases them, but they do not create / maintain them. If you report it directly to (URW++), you have much bigger chance of this issue actually getting fixed.... :)

**Comment by tillkamppeter** [comment]
Do you have a link to URW++, preferably to their bug tracking system?

**Comment by probonopd** [comment]
The (URW++) company does not exist anymore.

URW Type Foundry GmbH at https://www.urwtype.com/ is apparently now holding the assets of the former company, and has some of the same team.

**Comment by chris-liddell** [comment]
I will make some enquiries to see where we (Artifex) stand wrt to URW++.

**Comment by deekej** [comment]
> The (URW++) company does not exist anymore.
Wow, I didn't know that! :-O Sorry for the confusion!

**Comment by chris-liddell** [comment]
> > The (URW++) company does not exist anymore.
> 
> Wow, I didn't know that! :-O Sorry for the confusion!

It's a bit less dramatic than it sounds.

URW++ were bought out by Global Graphics PLC and have been operating as a Global Graphics subsidiary for about 4 years.

At present, Global are in the advanced stages of selling the URW++ business to Monotype. So "URW++" still exists, it's just not a stand alone business entity any more.

**Comment by probonopd** [comment]
Thanks for the correction, I mixed it up. Accorring to Wikipedia,

In 1995 the original URW conpany ceased to exist, and a new company, URW++ was founded. URW++ was sold to Global Graphics plc in 2016 and renamed URW Type Foundry GmbH in 2018. 

>  in the advanced stages of selling the URW++ business to Monotype

Wasn't aware of this. (Everything inside me screams "Noooooooo"!)

**Comment by chris-liddell** [comment]
For the record here, we got updated font files for this issue from URW++, and they look okay to me:
https://ghostscript.com/~chrisl/afii10084-glyph-bug/

I asked the original reporter on launchpad if they could double check the fix, but no response as yet. Will give it a few more days.

**Comment by probonopd** [comment]
Hi @chris-liddell since you seem to have the right contacts at URW to make things happen, maybe you could look into the following as well. I tried to open an issue at https://github.com/ArtifexSoftware/ghostpdl but seemingly there is no way to open an issue in that repository which is why I am asking here.

I understand that the fonts listed below had been released earlier by URW++ for free distribution with the APFL-licensed GhostPCL. It would be tremendously valuable if these could also be released in the same formats and under the same licenses as the fonts in  the Core 35.

_Some_ of these might be outdated because the Core 35 Font contain never versions with _similar_ names, but others (e.g., __U001__) are entirely missing in the Core 35 Fonts.

```
-rw-rw-r--  147400 2010-01-26 06:45 A028-Ext.ttf
-rw-rw-r--  143192 2010-01-26 06:45 A028-Med.ttf
-rw-rw-r--  129820 2010-01-26 06:45 A030-BolIta.ttf
-rw-rw-r--  135276 2010-01-26 06:45 A030-Bol.ttf
-rw-rw-r--  130448 2010-01-26 06:45 A030-Ita.ttf
-rw-rw-r--  132152 2010-01-26 06:45 A030-Reg.ttf
-rw-rw-r--  136120 2010-01-26 06:45 AntiqueOlive-Bol.ttf
-rw-rw-r--  125336 2010-01-26 06:45 AntiqueOlive-Ita.ttf
-rw-rw-r--  129872 2010-01-26 06:45 AntiqueOlive-Reg.ttf
-rw-rw-r--   91640 2008-07-15 00:08 ArtLinePrinter.ttf
-rw-rw-r--   90948 2010-01-26 06:45 CenturySchL-BoldItal.ttf
-rw-rw-r--   95828 2010-01-26 06:45 CenturySchL-Bold.ttf
-rw-rw-r--   92120 2010-01-26 06:45 CenturySchL-Ital.ttf
-rw-rw-r--   97004 2010-01-26 06:45 CenturySchL-Roma.ttf
-rw-rw-r--  161924 2010-01-26 06:45 ClarendonURW-BolCon.ttf
-rw-rw-r--  161720 2010-01-26 06:45 Coronet.ttf
-rw-rw-r--   58056 2008-07-15 00:08 Dingbats.ttf
-rw-rw-r--  175508 2008-07-15 00:08 GaramondNo8-Ita.ttf
-rw-rw-r--  175344 2010-01-26 06:45 GaramondNo8-MedIta.ttf
-rw-rw-r--  186000 2010-01-26 06:45 GaramondNo8-Med.ttf
-rw-rw-r--  185912 2010-01-26 06:45 GaramondNo8-Reg.ttf
-rw-rw-r--  137000 2008-07-15 00:08 LetterGothic-Bol.ttf
-rw-rw-r--  129924 2008-07-15 00:08 LetterGothic-Ita.ttf
-rw-rw-r--  129580 2008-07-15 00:08 LetterGothic-Reg.ttf
-rw-rw-r--  120116 2010-01-26 06:45 Mauritius-Reg.ttf
-rw-rw-r--   94184 2008-07-15 00:08 NimbusMonL-BoldObli.ttf
-rw-rw-r--   93968 2008-07-15 00:08 NimbusMonL-Bold.ttf
-rw-rw-r--   89352 2008-07-15 00:08 NimbusMonL-ReguObli.ttf
-rw-rw-r--   87236 2008-07-15 00:08 NimbusMonL-Regu.ttf
-rw-rw-r--  161500 2008-07-15 00:08 NimbusMono-BolIta.ttf
-rw-rw-r--  161896 2008-07-15 00:08 NimbusMono-Bol.ttf
-rw-rw-r--  152976 2008-07-15 00:08 NimbusMono-Ita.ttf
-rw-rw-r--  150584 2008-07-15 00:08 NimbusMono-Reg.ttf
-rw-rw-r--  155820 2010-01-26 06:45 NimbusRomanNo4-BolIta.ttf
-rw-rw-r--  161684 2010-01-26 06:45 NimbusRomanNo4-Bol.ttf
-rw-rw-r--  159200 2010-01-26 06:45 NimbusRomanNo4-LigIta.ttf
-rw-rw-r--  160140 2010-01-26 06:45 NimbusRomanNo4-Lig.ttf
-rw-rw-r--  155256 2010-01-26 06:45 NimbusRomanNo9-Ita.ttf
-rw-rw-r--  149208 2010-01-26 06:45 NimbusRomanNo9-MedIta.ttf
-rw-rw-r--  159624 2010-01-26 06:45 NimbusRomanNo9-Med.ttf
-rw-rw-r--  158804 2010-01-26 06:45 NimbusRomanNo9-Reg.ttf
-rw-rw-r--   91192 2010-01-26 06:45 NimbusRomNo9L-MediItal.ttf
-rw-rw-r--   93864 2010-01-26 06:45 NimbusRomNo9L-Medi.ttf
-rw-rw-r--   92372 2010-01-26 06:45 NimbusRomNo9L-ReguItal.ttf
-rw-rw-r--   94068 2010-01-26 06:45 NimbusRomNo9L-Regu.ttf
-rw-rw-r--   76452 2010-01-26 06:45 NimbusSanL-BoldCondItal.ttf
-rw-rw-r--   75872 2010-01-26 06:45 NimbusSanL-BoldCond.ttf
-rw-rw-r--  109168 2010-01-26 06:45 NimbusSanL-BoldItal.ttf
-rw-rw-r--  112744 2010-01-26 06:45 NimbusSanL-Bold.ttf
-rw-rw-r--   74912 2010-01-26 06:45 NimbusSanL-ReguCondItal.ttf
-rw-rw-r--   76988 2010-01-26 06:45 NimbusSanL-ReguCond.ttf
-rw-rw-r--  104992 2010-01-26 06:45 NimbusSanL-ReguItal.ttf
-rw-rw-r--  106572 2010-01-26 06:45 NimbusSanL-Regu.ttf
-rw-rw-r--   40528 2008-07-15 00:08 StandardSymL.ttf
-rw-rw-r--  125480 2010-01-26 06:45 U001-BolIta.ttf
-rw-rw-r--  131788 2010-01-26 06:45 U001-Bol.ttf
-rw-rw-r--  124016 2010-01-26 06:45 U001Con-BolIta.ttf
-rw-rw-r--  131964 2010-01-26 06:45 U001Con-Bol.ttf
-rw-rw-r--  124632 2010-01-26 06:45 U001Con-Ita.ttf
-rw-rw-r--  127892 2010-01-26 06:45 U001Con-Reg.ttf
-rw-rw-r--  125136 2010-01-26 06:45 U001-Ita.ttf
-rw-rw-r--  127312 2010-01-26 06:45 U001-Reg.ttf
-rw-rw-r--   88792 2010-01-26 06:45 URWBookmanL-DemiBoldItal.ttf
-rw-rw-r--   91668 2010-01-26 06:45 URWBookmanL-DemiBold.ttf
-rw-rw-r--   88896 2010-01-26 06:45 URWBookmanL-LighItal.ttf
-rw-rw-r--   91540 2010-01-26 06:45 URWBookmanL-Ligh.ttf
-rw-rw-r--   94372 2010-01-26 06:45 URWChanceryL-MediItal.ttf
-rw-rw-r--  141916 2010-01-26 06:45 URWClassico-BolIta.ttf
-rw-rw-r--  143780 2010-01-26 06:45 URWClassico-Bol.ttf
-rw-rw-r--  143032 2010-01-26 06:45 URWClassico-Ita.ttf
-rw-rw-r--  144608 2010-01-26 06:45 URWClassico-Reg.ttf
-rw-rw-r--   72912 2010-01-26 06:45 URWGothicL-BookObli.ttf
-rw-rw-r--   73908 2010-01-26 06:45 URWGothicL-Book.ttf
-rw-rw-r--   75220 2010-01-26 06:45 URWGothicL-DemiObli.ttf
-rw-rw-r--   77580 2010-01-26 06:45 URWGothicL-Demi.ttf
-rw-rw-r--   89340 2010-01-26 06:45 URWPalladioL-BoldItal.ttf
-rw-rw-r--   91864 2010-01-26 06:45 URWPalladioL-Bold.ttf
-rw-rw-r--   90308 2010-01-26 06:45 URWPalladioL-Ital.ttf
-rw-rw-r--   93168 2010-01-26 06:45 URWPalladioL-Roma.ttf
```

**Comment by chris-liddell** [comment]
> Hi @chris-liddell since you seem to have the right contacts at URW to make things happen, maybe you could look into the following as well. I tried to open an issue at https://github.com/ArtifexSoftware/ghostpdl but seemingly there is no way to open an issue in that repository which is why I am asking here.
> 
> I understand that the fonts listed below had been released earlier by URW++ for free distribution with the APFL-licensed GhostPCL. It would be tremendously valuable if these could also be released in the same formats and under the same licenses as the fonts in the Core 35.
> 
> _Some_ of these might be outdated because the Core 35 Font contain never versions with _similar_ names, but others (e.g., **U001**) are entirely missing in the Core 35 Fonts.
<SNIP>

In a word, "No". We have asked several times (even offered to pay) but no dice.

What you are asking about is the PCL5 font set and that's different fonts and different glyph collections and different metrics (although, as you imply, there is overlap) compared to the Postscript/PDF "core 35" font set. They are not "outdated", they are intentionally different to satisfy the different requirements.

I don't know for sure, but I strongly suspect the reason is that the PCL5 font set still represents a strong revenue stream for URW++ (in a way the Postscript set was never likely to be) so they are unwilling to move to a more permissive license that might (even potentially) risk that revenue.

**Comment by probonopd** [comment]
Too bad. I doubt it would even be noticeable in the balance sheet of Monotype (who are now buying URW). Anyway, thanks for checking @chris-liddell.

**Comment by chris-liddell** [comment]
Fixed:

https://github.com/ArtifexSoftware/urw-base35-fonts/commit/c15105598aa7eb256b1ebfcecd3d078801521e73

**Comment by apodtele** [comment]
See #35 for similar issues with other glyphs.
