### ISSUE TITLE
License & WOFF2

### ISSUE THREAD

**Issue by cdquest** [ArtifexSoftware/urw-base35-fonts#30]
Hi guys,

I plan to self-host fonts on a website, among others one of the URW-base35 fonts. The AGPLv3 license would allow me to redistribute it. 

Now I need to convert the font from OTF to WOFF2 format, for which I use Fontforge.

However, in Fontforge, the font info window gives the following copyright notice (thus embedded in the .otf file):
"
Copyright (URW)++,Copyright 2014 by (URW)++ Design & Development
"
Does this simply mean that this field was not updated when URW released the font under AGPLv3? And may I change that field into AGPLv3 myself? Or should I doubt whether I am entitled to change the format and/or distribute the font on a server?

Any other fields to consider?

**Comment by chris-liddell** [comment]
"Copyright" is not "License". You may *not* change the Copyright - regardless of the license involved (with the exception of "public domain" which, by definition does not have a copyright holder), the copyright holder does *not* change. NOTE: AGPL and GPL are "open source" *not* "public domain".

As far as I am aware, there is no standard way of embedding *license* information in a font.

**Comment by cdquest** [comment]
Thanks Chris, for pointing out that copyright and license are not the same thing. I overlooked that.

Leaving the copyright notice untouched, this apparently implies that it is not required to mention the license in the woff2 file itself. Anyone who needs it will find the license here.

Even if mentioning AGPLv3 is optional, it is possible in the "WOFF - metadata" or "comment" field.
