### ISSUE TITLE
Provide a better alias name for the "coded" font names

### ISSUE THREAD

**Issue by tbrowder** [ArtifexSoftware/urw-base35-fonts#50]
I would like to use these fonts, but some names give no hint as to what Adobe font they are substitutes for. For example, it would help to provide a listing something like this:

    URW Font file            replaces Adobe 
    file1                    adobe file1
    ...
    file35                   adobe file35

**Comment by fabiangreffrath** [comment]
Fontconfig may have the overview that you are looking for:

https://gitlab.freedesktop.org/fontconfig/fontconfig/-/blob/main/conf.d/30-metric-aliases.conf?ref_type=heads

**Comment by tbrowder** [comment]
Thanks so much!
